/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EVUNGLE_AUTODEFS_H
#define S3EVUNGLE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_VUNGLE_NAME "s3eVungle"
#define S3E_EXT_VUNGLE_HASH 0xd19eb261

#endif /* !S3EVUNGLE_AUTODEFS_H */
