/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eVungle.h"


// For MIPs (and WP8) platform we do not have asm code for stack switching 
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eVungleDefaultUserData_t)(s3eVungleUserData* out_userData);
typedef  s3eResult(*s3eVungleRegister_t)(s3eVungleCallback callbackID, s3eCallback callbackFn, void* userData);
typedef  s3eResult(*s3eVungleUnRegister_t)(s3eVungleCallback callbackID, s3eCallback callbackFn);
typedef       void(*s3eVungleStart_t)(const char* pubAppID);
typedef       void(*s3eVungleStartWithUserData_t)(const char* pubAppID, const s3eVungleUserData* userData);
typedef       void(*s3eVungleGetCurrentStatusData_t)(s3eVungleStatusData* out_statusData);
typedef    s3eBool(*s3eVungleIsRunning_t)();
typedef       void(*s3eVunglePrintCacheFiles_t)();
typedef       void(*s3eVunglePrintDeviceSettings_t)();
typedef const char*(*s3eVungleGetVersionString_t)();
typedef    s3eBool(*s3eVungleIsAdAvailable_t)();
typedef       void(*s3eVunglePlayModalAd_t)(s3eBool animate, s3eBool showClose);
typedef       void(*s3eVunglePlayIncentivizedAd_t)(s3eBool animate, s3eBool showClose, const char* userTag);
typedef      int32(*s3eVungleGetCacheSize_t)();
typedef       void(*s3eVungleSetCacheSize_t)(int32 megabytes);
typedef       void(*s3eVungleSetLogToStdout_t)(s3eBool state);
typedef       void(*s3eVungleSetSoundEnabled_t)(s3eBool enabled);
typedef       void(*s3eVungleSetMuteIfMusicIsPlaying_t)(s3eBool state);
typedef    s3eBool(*s3eVungleSetCustomCountDownText_t)(const char* text);
typedef       void(*s3eVungleSetAlertBoxSettings_t)(const char* title, const char* body, const char* leftButtonTitle, const char* rightButtonTitle);
typedef       void(*s3eVungleSetAllowAutoRotate_t)(s3eBool allow);

/**
 * struct that gets filled in by s3eVungleRegister
 */
typedef struct s3eVungleFuncs
{
    s3eVungleDefaultUserData_t m_s3eVungleDefaultUserData;
    s3eVungleRegister_t m_s3eVungleRegister;
    s3eVungleUnRegister_t m_s3eVungleUnRegister;
    s3eVungleStart_t m_s3eVungleStart;
    s3eVungleStartWithUserData_t m_s3eVungleStartWithUserData;
    s3eVungleGetCurrentStatusData_t m_s3eVungleGetCurrentStatusData;
    s3eVungleIsRunning_t m_s3eVungleIsRunning;
    s3eVunglePrintCacheFiles_t m_s3eVunglePrintCacheFiles;
    s3eVunglePrintDeviceSettings_t m_s3eVunglePrintDeviceSettings;
    s3eVungleGetVersionString_t m_s3eVungleGetVersionString;
    s3eVungleIsAdAvailable_t m_s3eVungleIsAdAvailable;
    s3eVunglePlayModalAd_t m_s3eVunglePlayModalAd;
    s3eVunglePlayIncentivizedAd_t m_s3eVunglePlayIncentivizedAd;
    s3eVungleGetCacheSize_t m_s3eVungleGetCacheSize;
    s3eVungleSetCacheSize_t m_s3eVungleSetCacheSize;
    s3eVungleSetLogToStdout_t m_s3eVungleSetLogToStdout;
    s3eVungleSetSoundEnabled_t m_s3eVungleSetSoundEnabled;
    s3eVungleSetMuteIfMusicIsPlaying_t m_s3eVungleSetMuteIfMusicIsPlaying;
    s3eVungleSetCustomCountDownText_t m_s3eVungleSetCustomCountDownText;
    s3eVungleSetAlertBoxSettings_t m_s3eVungleSetAlertBoxSettings;
    s3eVungleSetAllowAutoRotate_t m_s3eVungleSetAllowAutoRotate;
} s3eVungleFuncs;

static s3eVungleFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xd19eb261, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eVungle");
            
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xd19eb261, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eVungleAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eVungleDefaultUserData(s3eVungleUserData* out_userData)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[0] func: s3eVungleDefaultUserData"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleDefaultUserData(out_userData);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

s3eResult s3eVungleRegister(s3eVungleCallback callbackID, s3eCallback callbackFn, void* userData)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[1] func: s3eVungleRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eVungleRegister(callbackID, callbackFn, userData);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult s3eVungleUnRegister(s3eVungleCallback callbackID, s3eCallback callbackFn)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[2] func: s3eVungleUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eVungleUnRegister(callbackID, callbackFn);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eVungleStart(const char* pubAppID)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[3] func: s3eVungleStart"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleStart(pubAppID);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleStartWithUserData(const char* pubAppID, const s3eVungleUserData* userData)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[4] func: s3eVungleStartWithUserData"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleStartWithUserData(pubAppID, userData);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleGetCurrentStatusData(s3eVungleStatusData* out_statusData)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[5] func: s3eVungleGetCurrentStatusData"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleGetCurrentStatusData(out_statusData);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

s3eBool s3eVungleIsRunning()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[6] func: s3eVungleIsRunning"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eBool ret = g_Ext.m_s3eVungleIsRunning();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eVunglePrintCacheFiles()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[7] func: s3eVunglePrintCacheFiles"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVunglePrintCacheFiles();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVunglePrintDeviceSettings()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[8] func: s3eVunglePrintDeviceSettings"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVunglePrintDeviceSettings();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

const char* s3eVungleGetVersionString()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[9] func: s3eVungleGetVersionString"));

    if (!_extLoad())
        return NULL;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_s3eVungleGetVersionString();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eBool s3eVungleIsAdAvailable()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[10] func: s3eVungleIsAdAvailable"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eBool ret = g_Ext.m_s3eVungleIsAdAvailable();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eVunglePlayModalAd(s3eBool animate, s3eBool showClose)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[11] func: s3eVunglePlayModalAd"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVunglePlayModalAd(animate, showClose);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVunglePlayIncentivizedAd(s3eBool animate, s3eBool showClose, const char* userTag)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[12] func: s3eVunglePlayIncentivizedAd"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVunglePlayIncentivizedAd(animate, showClose, userTag);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

int32 s3eVungleGetCacheSize()
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[13] func: s3eVungleGetCacheSize"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    int32 ret = g_Ext.m_s3eVungleGetCacheSize();

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eVungleSetCacheSize(int32 megabytes)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[14] func: s3eVungleSetCacheSize"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetCacheSize(megabytes);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleSetLogToStdout(s3eBool state)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[15] func: s3eVungleSetLogToStdout"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetLogToStdout(state);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleSetSoundEnabled(s3eBool enabled)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[16] func: s3eVungleSetSoundEnabled"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetSoundEnabled(enabled);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleSetMuteIfMusicIsPlaying(s3eBool state)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[17] func: s3eVungleSetMuteIfMusicIsPlaying"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetMuteIfMusicIsPlaying(state);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

s3eBool s3eVungleSetCustomCountDownText(const char* text)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[18] func: s3eVungleSetCustomCountDownText"));

    if (!_extLoad())
        return S3E_FALSE;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eBool ret = g_Ext.m_s3eVungleSetCustomCountDownText(text);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eVungleSetAlertBoxSettings(const char* title, const char* body, const char* leftButtonTitle, const char* rightButtonTitle)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[19] func: s3eVungleSetAlertBoxSettings"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetAlertBoxSettings(title, body, leftButtonTitle, rightButtonTitle);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

void s3eVungleSetAllowAutoRotate(s3eBool allow)
{
    IwTrace(VUNGLE_VERBOSE, ("calling s3eVungle[20] func: s3eVungleSetAllowAutoRotate"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eVungleSetAllowAutoRotate(allow);

#ifdef LOADER_CALL
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
